version: "3"

services:

   boot_server:
      image: boot-image
      networks:
         - my-net
      ports:
         - 7070:8080
      depends_on: 
         - db_server

   db_server:
      image: db-boot-image
      restart: always
      networks:
         - my-net
      environment:
         - DB_ENVIRONMENT_VARIABLE=any_value

networks:
   my-net:

