version: "3"

services:

   boot_server-test:
      image: boot-image-test
      networks:
         - my-net
      ports:
         - 7070:8080
      depends_on: 
         - db_server-test

   db_server-test:
      image: db-boot-image-test
      networks:
         - my-net
      environment:
         - DB_ENVIRONMENT_VARIABLE=any_value

networks:
   my-net:

